# Object Oriented Programming (OOP) on Python

<r>

#### Time to abstract ourselves.👾

![](IMG/poo.jpeg)

![print(ja)*999](IMG/poo%20meme.jpeg)
(okno XD)

Referencias: https://docs.hektorprofe.net/python/programacion-orientada-a-objetos/ejercicios/

### Ejercicio 1:
Escriba un programa Python para crear una clase que represente un círculo. Incluir métodos para calcular su área y perímetro.

![](IMG/circulo.jpeg)

In [126]:
from math import pi
class Circle(object): 
    def __init__(self, center = (0,0), radius = 1):
        if type(center) == tuple and (type(radius) == int or type(radius) == float):
            self.center = center
            self.radius = radius
        else:
            print("Center debe ser de tipo tupla y radius de tipo int o float")
    def __str__(self) -> str:
        return f"Centro = {self.center}\nRadio = {self.radius}"
    
    @property
    def diameter(self):
        return 2*self.radius
    
    @property
    def area(self):#Area
        return pi * (self.radius)**2
    
    @property
    def perimeter(self):#Perimetro
        return self.diameter * pi
    
#Prueba: 
c = Circle((3,3),5)
print(c)
print("Diametro =",c.diameter)
print("Area =",c.area)
print("Perimetro =",c.perimeter)

Centro = (3, 3)
Radio = 5
Diametro = 10
Area = 78.53981633974483
Perimetro = 31.41592653589793


### Ejercicio 2:
Escriba un programa Python para crear una clase de persona. Incluya atributos como nombre, país y fecha de nacimiento. Implementar un método para determinar la edad de la persona.

![](IMG/persona.jpeg)(JSJJASKJA juro que me baño a veces)

In [5]:
#Con datetime
from datetime import date
class Persona(object):
    def __init__(self, nombre, pais, fecha_de_nacimiento):
        if type(nombre) == str and type(pais) == str and type(fecha_de_nacimiento) == date:  
            self.nombre = nombre
            self.pais = pais
            self.fecha_de_nacimiento = fecha_de_nacimiento
        else:
            print("Los valores de entrada no corresponden con el tipo esperado.\ntype(nombre) == str and type(pais) == str and type(fecha_de_nacimiento) == date")
    def __str__(self) -> str:
        return "Nombre: {}\nPais: {}\nFecha de Nacimiento: {}".format(self.nombre, self.pais, self.fecha_de_nacimiento)

    @property
    def calcular_edad(self):
        today = date.today()
        years_old = today.year - self.fecha_de_nacimiento.year
        if (today.month, today.day) < (self.fecha_de_nacimiento.month, self.fecha_de_nacimiento.day):
            years_old -= 1
        return years_old

#Prueba: 
persona5 = Persona("Akira Kurusu/Ren Amamiya(Joker)", "Japon, Tokio", date(2000, 10, 2))
print(f"Nombre: {persona5.nombre}")
print(f"Pais: {persona5.pais}")
print(f"Fecha de Nacimiento: {persona5.fecha_de_nacimiento}")
edad = persona5.calcular_edad
print(f"Edad: {edad} años")


Nombre: Akira Kurusu/Ren Amamiya(Joker)
Pais: Japon, Tokio
Fecha de Nacimiento: 2000-10-02
Edad: 23 años


### Ejercicio 3:
Escriba un programa Python para crear una clase de calculadora. Incluir métodos para operaciones aritméticas básicas.

![](IMG/calculadora.png)

In [322]:
class Calculadora(object):
    def __init__(self):
        self.historial = []
        pass

    def suma(self, *numeros):
        resultado = numeros[0]
        for num in numeros[1:]:
            temp = resultado
            resultado += num
            self.historial.append(("+",temp,num,resultado))    
        return resultado

    def resta(self, *numeros):
        resultado = numeros[0]
        for num in numeros[1:]:
            temp = resultado
            resultado -= num
            self.historial.append(("-",temp,num,resultado))    
        return resultado

    def multiplicacion(self, *numeros):
        resultado = 1
        for num in numeros:
            temp = resultado
            resultado *= num
            self.historial.append(("*",temp,num,resultado))    
        return resultado

    def division(self, *numeros):
        divisor = numeros[1]
        resultado = numeros[0] / divisor
        self.historial.append(("/",numeros[0],divisor,resultado)) 
        for i in range(2, len(numeros)):
            temp = resultado
            divisor = numeros[i]
            resultado /= divisor
            self.historial.append(("/",temp,divisor,resultado)) 
        return resultado
    
    def __str__(self):
        return f"===Historial===\n{self.historial}"
    
    def registro(self,val):
        found = []
        for operation in self.historial:
            if val in operation:
                found.append(operation)
        if len(found)==0:
            return f"El valor {val} no se encontró en el historial"
        return f"===Registro===\nResultados: {found}"

# Ejemplo de uso
calculadora = Calculadora()

print("Suma:", calculadora.suma(5, 3, 2))
print("Resta:", calculadora.resta(10, 4, 3))
print("Multiplicación:", calculadora.multiplicacion(6, 7, 8))
print("División:", calculadora.division(20, 5, 2, 4))
print(calculadora)
print(calculadora.registro(5))

Suma: 10
Resta: 3
Multiplicación: 336
División: 0.5
===Historial===
[('+', 5, 3, 8), ('+', 8, 2, 10), ('-', 10, 4, 6), ('-', 6, 3, 3), ('*', 1, 6, 6), ('*', 6, 7, 42), ('*', 42, 8, 336), ('/', 20, 5, 4.0), ('/', 4.0, 2, 2.0), ('/', 2.0, 4, 0.5)]
===Registro===
Resultados: [('+', 5, 3, 8), ('/', 20, 5, 4.0)]


### Ejercicio 4:
Escriba un programa Python para crear una clase que represente un carrito de compras. Incluya métodos para agregar y quitar artículos y calcular el precio total.

![](IMG/carrito%20shipo.jpeg)

In [65]:
class CarritoMagico(object):
    def __init__(self):
        self.almacen = {"ᚺ" : ["Cepillo de Dientes Mágico" ,19.99, 3, "Cambia el color de tus dientes a cualquier tono deseado en segundos."],
                        "ᚲ" : ["Libro de Dormir Mágico", 29.99, 2 ,"Aprende programación orientada a objetos mientras duermes, garantizando que nunca olvides lo que leiste"],
                        "ᛁ" : ["Pantalones Mágicos", 49.99, 5 ,"Cambian de color automáticamente según tu estado de ánimo"],
                        "ᚻ"  : ["Gafas Mágicas", 39.99, 4 ,"Te permiten ver el futuro (solo hasta el final del día)"],
                        "ᚱ" : ["Perro Robot Mágico", 89.99, 1, "Cocina tus comidas mientras juega contigo"],
                        "ᚳ" : ["Sofá Mágico", 59.99, "Cambia de tamaño para adaptarse a cualquier habitación"],
                        "ᚸ" : ["Jabón Mágico", 14.99, 6, "Limpia cualquier mancha, incluso las que están ocultas a simple vista"],
                        "ᛂ": ["Zapatillas Mágicas", 34.99, 2, "Hacen que camines sin cansarte, perfectas para largas jornadas de shopping"],
                        "ᚴ": ["Ropa Interior Mágica" , 39.99, 3, "Cambia de talla automáticamente para ajustarse a tu cuerpo"],
                        "ᚾ": ["Caja Mágica", 49.99, 2, "Contiene un objeto completamente diferente cada vez que la abres"],
                        "ᚼ": ["Mascara Mágica",  29.99, 4, "Cambia tu apariencia instantáneamente, ideal para días rápidos."],
                        "ᚷ": ["Cuchillo Mágico", 24.99, 5, "Corta cualquier cosa, incluso el aire."], 
                        "ᚹ" :["Reloj Magico", 49.99, 1, "Retrocede en tiempo para evitar retrasos, adelántate para llegar primero."]}
        self.simbolos = list(self.almacen.keys())
        self.historial = []
        self.carrito = {}
        self.bolsillo = 200.00
        '''
        Clase de compras magicas. Te encuentras en una tarde de verano durante un posible evento de esquizofrenia a un viejo sabio mercader de barba larga y tendida, deambulando por las calles de tu 
        zona y con un letrero llamativo de carton que tiene escrito "Productos Magicos"
            Situacion:
                Te encuentras desesperado, sales a coger un aire en busca de alguna epifania pues no consigues salir adelante con uno de los ejercicios de POO en Python, te encuentras frustrado,
                has estado descuidando tu cuidado higienico personal y del hogar. Vives solo pero en estos momentos te preocupa mas encontrar la solucion al ejercicio que te perturba que ducharte
                y limpiar tu casa. Cuentas con $200.00 en el bolsillo y frente al vendedor magico ambulante ahora puede que encuentres la solucion a tu problema.
            Constructor:
                * Almacen => Diccionario que utiliza como llaves y IDs de cada producto runas nórdicas como códigos de productos. Cada runa representa un producto mágico distinto. 
                Por ejemplo, ᚱ podría representar el "Cepillo de Dientes Mágico", ᚲ el "Libro de Dormir Mágico", etc. Y que tiene como valores una lista cuyos elementos estan organizados en:
                    lista[0] => Nombre del producto
                    lista[1] => Precio
                    lista[2] => Cantidad de producto
                    lista[3] => Descripcion del producto 
            Propiedades: 
                * .sumbolos => devuelve todas las runas
                * .articulos => imprime los articulos del almacen con su nombre, precio y disponiblidad
                * .inventario => imprime el diccionario del almacen y el del carrito
            Metodos:
                * .description(ID) => recibe por parametro una runa (ID) y si se encuentra dentro del almacen devuelve su descripcion
                * .agregar(ID, n) => recibe por parametro la runa correspondiente al articulo (ID) y la cantidad que se desea agregar al carrito (n) y lo agrega si cumple las condiciones:
                    -que el parametro ID reciba una runa valida
                    -que el parametro n no reciba una cantidad mayor a la disponble en el almacen
                    -que el dinero en la billetera sea suficiente para pagar el monto total del precio del articulo multiplicado por la cantidad
                * .devolver(ID, n) => recibe por parametro la runa correspondiente al articulo (ID) y la cantidad que se desea devolver al almacen (n) y lo agrega si cumple las condiciones:
                    -que el parametro ID reciba una runa que se encuentre dentro del carrito
                    -que el parametro n no reciba una cantidad mayor a la disponble en el carrito
                * __str__ => Devuelve el historial de compras y devoluciones
        '''

    def descripcion(self,ID):
        if ID not in self.simbolos:
            raise ValueError("El valor insertado no corresponde con ningun ID")
        return f"Descripcion del {self.almacen[ID][0]}: {self.almacen[ID][-1]}"
    
    @property
    def simbols(self):
        return self.simbolos
    
    @property
    def articulos(self):
        almacen = list(self.almacen.values())
        print("===Articulos===")
        for index in range(len(almacen)):
            print(f"Nombre(Runa => {self.simbolos[index]}): {almacen[index][0]}\nPrecio: ${almacen[index][1]}\nDisponibilidad: {almacen[index][2]}\n")
        return ""

    
    @property
    def inventario(self):
        print(f"\t===Almacen=== \n{self.almacen}\n\t===Carrito=== \n{self.carrito}")
        return "\n"
        
    
    @property
    def billetera(self):
        print(f"\t====Bolsillo=== \n${self.bolsillo}")
        return ""
    
    def agregar(self, ID, n):
        if ID not in self.simbolos:
            raise ValueError("El valor insertado no corresponde con ningun ID existente")
        if n > self.almacen[ID][2]:
            raise ValueError("La cantidad introducida es mayor a la disponibilidad en el almacen")
        if self.bolsillo < self.almacen[ID][1]*n:
            raise ValueError("No tienes dinero suficiente en tu bolsillo para pagar el monto total")
        self.bolsillo -= self.almacen[ID][1]*n
        self.carrito[ID] = self.almacen[ID]
        self.almacen[ID][2] -= n
        if self.almacen[ID][2] == 0:
            self.almacen.pop(ID)
        add = ("carrito","+",ID, n)
        self.historial.append(add)
        self.carrito[ID][2] = n
        print(f"Operacion {add} efectuada con exito. Dinero actual: ${self.bolsillo}.\n")
        pass
    
    def devolver(self, ID, n):
        if len(list(self.carrito)) > 0:
            if ID not in self.carrito:
                raise ValueError("El valor insertado no corresponde con ningun ID existente")
            if n > self.carrito[ID][2]:
                raise ValueError("La cantidad introducida es mayor a la presente en el carrito")
            
            self.bolsillo += self.carrito[ID][1] * n
            if ID in self.almacen:
                self.almacen[ID][2] += n
            else:
                self.almacen[ID] = self.carrito[ID]
                self.almacen[ID][2] = n
            self.carrito[ID][2] -= n
        if self.carrito[ID][2] == 0:
            self.carrito.pop(ID)
        less = ("carrito","-",ID, n)
        self.historial.append(less)
        print(f"Operacion {less} efectuada con exito. Dinero actual: ${self.bolsillo}.\n")
        pass

    @property
    def conclusion(self):
        if "ᚲ" in self.carrito:
            print("Perfecto, ahora solo bastarian un par de noches de sueño y como dice el dicho, la solucion de los problemas que no te llega desperto te llega durante el sueño")
    
    def __str__(self) -> str:
        print(f"\t===Historial===\n{self.historial}")
        return ""
    
#Ejemplo desarrollo
carrito = CarritoMagico()
print(carrito.inventario) #Imprimiendo inventario 
print(carrito.simbolos) #Verificando runas
print(carrito.articulos)
print(carrito.descripcion('ᚲ')) #Verificando descripcion productos
print(carrito.billetera) #Verificando bolsillo
carrito.agregar('ᚲ',1) #Agregando libro de programacion
print(carrito.billetera) #Verificando billetera
carrito.agregar("ᚱ", 1) #Agregando el Perro Robot Magico
print(carrito.billetera) # Verificando billetera
print(carrito.inventario) #Verificando inventario despues de agregar el Perro Robot Magico
print(carrito.billetera) #Verificando la billetera despues de agregar el Perro Robot Magico
carrito.devolver("ᚱ", 1) #Devolviendo el Perro Robot Magico
print(carrito.inventario) #Verificando inventario despues de devolver el Perro Robot Magico
print(carrito.billetera) #Verificando bolsillo despues de devolver el Perro Robot Magico
print(carrito) #Imprimiendo historial
carrito.conclusion




	===Almacen=== 
{'ᚺ': ['Cepillo de Dientes Mágico', 19.99, 3, 'Cambia el color de tus dientes a cualquier tono deseado en segundos.'], 'ᚲ': ['Libro de Dormir Mágico', 29.99, 2, 'Aprende programación orientada a objetos mientras duermes, garantizando que nunca olvides lo que leiste'], 'ᛁ': ['Pantalones Mágicos', 49.99, 5, 'Cambian de color automáticamente según tu estado de ánimo'], 'ᚻ': ['Gafas Mágicas', 39.99, 4, 'Te permiten ver el futuro (solo hasta el final del día)'], 'ᚱ': ['Perro Robot Mágico', 89.99, 1, 'Cocina tus comidas mientras juega contigo'], 'ᚳ': ['Sofá Mágico', 59.99, 'Cambia de tamaño para adaptarse a cualquier habitación'], 'ᚸ': ['Jabón Mágico', 14.99, 6, 'Limpia cualquier mancha, incluso las que están ocultas a simple vista'], 'ᛂ': ['Zapatillas Mágicas', 34.99, 2, 'Hacen que camines sin cansarte, perfectas para largas jornadas de shopping'], 'ᚴ': ['Ropa Interior Mágica', 39.99, 3, 'Cambia de talla automáticamente para ajustarse a tu cuerpo'], 'ᚾ': ['Caja Mágica', 49.9

### Ejercicio 5:
Escriba un programa Python para crear una clase que represente un array de numpy. Incluya métodos para sumarse, restarse, multiplicarse y dividirse tal cual sucederia en un array de numpy

![](IMG/arr.jpg)

In [277]:
class Array:
    def __init__(self, data):
        self.data = data

    def __add__(self, other):
        if isinstance(other, Array):
            if len(self.data)!= len(other.data):
                raise ValueError("Los arrays deben tener la misma longitud o uno de ellos un array de 1D con el numero de elementos iguales al numero de filas de otro array")
            # Manejo de arrays 1D y 2D
            if isinstance(self.data[0], list):  # Suponiendo que self.data y other.data son 2D
                result = [[self[i][j] + other[i][j] for j in range(len(self.data[0]))] for i in range(len(self.data))]
                return Array(result)
            if (isinstance(self.data[0], (int,float))) and (isinstance(other.data[0], (list,tuple,Array))):
                result = [[self[i] + other[i][j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            if isinstance(other.data[0], (int,float)) and (isinstance(other.data[0], (list,tuple,Array))):
                result = [[self[i][j] + other[j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            else:  # Suponiendo que self.data y other.data son 1D
                result = [self[i] + other[i] for i in range(len(self.data))]
                return Array(result)
        elif isinstance(other, (int, float)):
            result = [x + other for x in self.data]
            return Array(result)
        else:
            raise TypeError("Operación de suma no soportada con este tipo de dato")
        

    def __sub__(self, other):
        if isinstance(other, Array):
            if len(self.data)!= len(other.data):
                raise ValueError("Los arrays deben tener la misma longitud o uno de ellos un array de 1D con el numero de elementos iguales al numero de filas de otro array")
            # Manejo de arrays 1D y 2D
            if isinstance(self.data[0], list):  # Suponiendo que self.data y other.data son 2D
                result = [[self[i][j] - other[i][j] for j in range(len(self.data[0]))] for i in range(len(self.data))]
                return Array(result)
            if (isinstance(self.data[0], (int,float))) and (isinstance(other.data[0], (list,tuple,Array))):
                result = [[self[i] - other[i][j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            if isinstance(other.data[0], (int,float)) and (isinstance(other.data[0], (list,tuple,Array))):
                result = [[self[i][j] - other[j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            else:  # Suponiendo que self.data y other.data son 1D
                result = [self[i] - other[i] for i in range(len(self.data))]
                return Array(result)
        elif isinstance(other, (int, float)):
            result = [x - other for x in self.data]
            return Array(result)
        else:
            raise TypeError("Operación de suma no soportada con este tipo de dato")

    def __mul__(self, other):
        if isinstance(other, Array):
            if len(self.data)!= len(other.data):
                raise ValueError("Los arrays deben tener la misma longitud o uno de ellos un array de 1D con el numero de elementos iguales al numero de filas de otro array")
            # Manejo de arrays 1D y 2D
            if isinstance(self.data[0], list):  # Suponiendo que self.data y other.data son 2D
                result = [[self[i][j] * other[i][j] for j in range(len(self.data[0]))] for i in range(len(self.data))]
                return Array(result)
            if (isinstance(self.data[0], (int,float))) and (isinstance(other.data[0], (list,tuple,Array))):
                result = [[self[i] * other[i][j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            if isinstance(other.data[0], (int,float)) and (isinstance(other.data[0], (list,tuple,Array))):
                result = [[self[i][j] * other[j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            else:  # Suponiendo que self.data y other.data son 1D
                result = [self[i] * other[i] for i in range(len(self.data))]
                return Array(result)
        elif isinstance(other, (int, float)):
            result = [x * other for x in self.data]
            return Array(result)
        else:
            raise TypeError("Operación de suma no soportada con este tipo de dato")
    
    def __matmul__(self, other):
        if isinstance((self,other),(list,tuple,Array)):
            if isinstance(self,(list,tuple,Array)) and isinstance(other[0],(list,tuple,Array)):
                if (len(self.data)!= len(other.data[0])):
                    raise ValueError("Las matrices no pueden multiplicarse si el número de columnas de la primera no coincide con el número de filas de la segunda")
                if (len(self.data)== len(other.data[0])):
                    result = []
                    for i in range(len(self.data)):
                        result.append([])
                        for j in range(len(other.data[0])):
                            product = 0
                            for k in range(len(self.data[0])):
                                product+= self.data[i][k] * other.data[k][j]
                            result[i].append(product)
                    return Array(result)                        
            if isinstance(self[0],(list,tuple,Array)) and isinstance(other,(list,tuple,Array)):
                if (len(self.data[0])== len(other.data)):
                    result = []
                    for i in range(len(other.data)):
                        result.append([])
                        for j in range(len(self.data[0])):
                            product = 0
                            for k in range(len(other.data[0])):
                                product+= other.data[i][k] * self.data[k][j]
                            result[i].append(product)   
                    return Array(result)
            else: 
                raise TypeError("Operación de suma no soportada con este tipo de dato")
        else:
            raise TypeError("Operación de suma no soportada con este tipo de dato")
        
    def __truediv__(self, other):
        if isinstance(other, (Array)):
            if len(self.data)!= len(other.data):
                raise ValueError("Los arrays deben tener la misma longitud o uno de ellos un array de 1D con el numero de elementos iguales al numero de filas de otro array")
            # Manejo de arrays 1D y 2D
            if isinstance(self[0], list):  # Suponiendo que self.data y other.data son 2D
                result = [[self[i][j] / other[i][j] for j in range(len(self.data[0]))] for i in range(len(self.data))]
                return Array(result)
            if (isinstance(self[0], (int,float))) and (isinstance(other[0], (list,tuple,Array))):
                result = [[self[i] / other[i][j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            if isinstance(other.data[0], (int,float)) and (isinstance(other.data[0], (list,tuple,Array))):
                result = [[self[i][j] / other[j] for j in range(len(self.data))] for i in range(len(other.data[0]))]
                return Array(result)
            else:  # Suponiendo que self.data y other.data son 1D
                result = [self[i] / other[i] for i in range(len(self.data))]
                return Array(result)
        elif isinstance(other, (int, float)):
            result = [x / other for x in self.data]
            return Array(result)
        else:
            raise TypeError("Operación de suma no soportada con este tipo de dato")

    def __getitem__(self, index):
        if isinstance(index, int):
            return self.data[index]
        elif isinstance(index, slice):
            return Array(self.data[index])
        else:
            raise IndexError("Índice fuera de rango")

    def __len__(self):
        return len(self.data)

    def __repr__(self):
        if isinstance(self.data[0], list):  # Caso de un array 2D
            out = '\n'.join(', '.join(map(str, row)) for row in self.data)
            out = str(out).replace(",", " ").replace("\n", "]\n[")
            return f"[[{out}]]"
        if isinstance(self.data, list):  # Caso de un array 1D
            out = ', '.join(map(str, self.data))
            out = str(out).replace(",", "")
            return f"[{out}]"

# Ejemplo:
one_dim_array = Array([1, 2, 3])
two_dim_array = Array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array 1D:\n",one_dim_array,
    "\n===Suma de arrays 1D a si mismo===\n", one_dim_array + one_dim_array,
    "\n===Resta de array 1D a si mismo===\n", one_dim_array - one_dim_array,
    "\n===Producto simple de array 1D con el mismo===\n", one_dim_array * one_dim_array,
    "\n===Division de array 1D con el mismo===\n",one_dim_array / one_dim_array,
    "\n\nArray 2D:\n",two_dim_array,
    "\n===Suma de un array 2D con el mismo===\n", two_dim_array+ two_dim_array,
    "\n===Resta de un array 2D con el mismo===\n", two_dim_array - two_dim_array,
    "\n===Producto simple de un array 2D con el mismo===\n", two_dim_array * two_dim_array,
    "\n===Division de un array 2D con el mismo===\n", two_dim_array / two_dim_array,
    "\n===Producto matricial de un array 2D con el mismo===\n",two_dim_array @ two_dim_array)



Array 1D:
 [1 2 3] 
===Suma de arrays 1D a si mismo===
 [2 4 6] 
===Resta de array 1D a si mismo===
 [0 0 0] 
===Producto simple de array 1D con el mismo===
 [1 4 9] 
===Division de array 1D con el mismo===
 [1.0 1.0 1.0] 

Array 2D:
 [[1  2  3]
[4  5  6]
[7  8  9]] 
===Suma de un array 2D con el mismo===
 [[2  4  6]
[8  10  12]
[14  16  18]] 
===Resta de un array 2D con el mismo===
 [[0  0  0]
[0  0  0]
[0  0  0]] 
===Producto simple de un array 2D con el mismo===
 [[1  4  9]
[16  25  36]
[49  64  81]] 
===Division de un array 2D con el mismo===
 [[1.0  1.0  1.0]
[1.0  1.0  1.0]
[1.0  1.0  1.0]] 
===Producto matricial de un array 2D con el mismo===
 [[30  36  42]
[66  81  96]
[102  126  150]]


#### Ejercicio 6:
Crea una clase llamada `RationalNumber` que tenga como atributos `numerator` y `denominator`, este ultimo con 1 como valor por defecto. Ambos atributos deben ser enteros.

![](IMG/racionales.jpeg)

Ademas, la implementacion debe incluir los siguientes metodos:
* `__str__` para poder imprimir los valores la fraccion en cuestion
* `.mathFormat` que muestre la fraccion en formato $LaTeX$. (Implementalo como propiedad)
* `.quotient` que devuelva el cociente (Implementalo como propiedad)
* `.isInfinite` que devuelva si el denominador es 0 o no
* `.simplify` que simplifique la fraccion a la fraccion irreducible.
* `.sum` donde: $$\frac{p_{1}}{q_{1}} + \frac{p_{2}}{q_{2}} = \frac{p_{1}q_{2} + p_{2}q_{1}}{q_{1} \cdot q_{2}}$$
* `.subract` donde: $$\frac{p_{1}}{q_{1}} - \frac{p_{2}}{q_{2}} = \frac{p_{1}q_{2} - p_{2}q_{1}}{q_{1} \cdot q_{2}}$$
* `.product` donde: $$\frac{p_{1}}{q_{1}} \cdot \frac{p_{2}}{q_{2}} = \frac{p_{1} \cdot p_{2}}{q_{1} \cdot q_{2}}$$
* `.division` donde: $$\frac{p_{1}}{q_{1}} \cdot \frac{p_{2}}{q_{2}} = \frac{p_{1} \cdot q_{2}}{q_{1} \cdot p_{2}}$$
* `.random()` que se encarga de crear un objeto aleatorio de la clase `RationalNumber`.
* `.zero()` que se encarga de crear el objeto de la clase `RationalNumber` que tiene por numerador 0 y denominador 1.
* `.one()` que se encarga de crear el objeto de la clase `RationalNumber` que tiene por numerador 1 y denominador 1.
* `.fromRealNumber()` que dado un número real se encarga de buscar su expresión en racional. Por ejemplo, dado 5.4, tendremos que crear el objeto `RationalNumber` con numerador 54 y denominador 10. Investiga el método `math.modf()` para este caso.


In [188]:
import math
class RationalNumber(object):
    '''
    Clase para trabajar con numeros racionales
    '''
    def __init__(self,n,d = 1):
        if type(n) is int and type(d) is int:
            self.numerator = n
            self.denominator = d
        else:
            print("El numerador y el denominador deben ser numeros enteros")
    
    def __str__(self):
        return (f"{self.numerator} / {self.denominator}")
    
    @property
    def mathFormat(self):
        from IPython.display import display, Latex
        display(Latex(f"${self.numerator} \\over {self.denominator}$"))

    @property
    def quotient(self):
        return self.numerator / self.denominator
    
    def isInfinite(self):
        return False if self.denominator != 0 else True
    
    def simplify(self):
        from numpy import gcd#Metodo de Numpy para hallar el mcd
        div = gcd(self.numerator, self.denominator)
        if div > 1:
            new_numerator = self.numerator / div
            new_denominator = self.denominator / div
            return ("Fraccion resultante simplificada: \n{} / {}".format(new_numerator,new_denominator))
        return "La fraccion es irreducible"
    
    @staticmethod
    def sum(p,q):
        new_num = (p.numerator * q.denominator) + (q.numerator * p.denominator)
        new_den = p.denominator * q.denominator
        print("{} / {} = {}".format(new_num,new_den,new_num / new_den))
    
    @staticmethod
    def substract(p,q):
        new_num = (p.numerator * q.denominator) - (q.numerator * p.denominator)
        new_den = p.denominator * q.denominator
        print("{} / {} = {}".format(new_num,new_den,new_num / new_den))
    
    @staticmethod
    def product(p,q):
        new_num = p.numerator * q.numerator
        new_den = p.denominator * q.denominator
        print("{} / {} = {}".format(new_num,new_den,new_num / new_den))
    
    @staticmethod
    def division(p,q):
        new_num = p.numerator * q.denominator
        new_den = p.denominator * q.numerator
        print("{} / {} = {}".format(new_num,new_den,new_num / new_den))

    @classmethod
    def random(cls):
        from numpy import random
        n = random.randint(1,100)
        d = random.randint(1,100)
        return cls(n,d)
    
    @classmethod
    def zero(cls):
        return cls(0)
    
    @classmethod
    def one(cls):
        return cls(1)
    
    @classmethod
    def fromRealNumber(cls,f):
        num = f
        den = 1
        d, i = math.modf(num)
        while d != 0:
            num *= 10
            den *= 10
            d, i = math.modf(num)
        num = int(num)
        den = int(den)
        return cls(num,den)
    
# Pruebas:
rational1 = RationalNumber(16, 4)
print(rational1)
print(rational1.isInfinite())  


# Simplificando la fracción
simplified = rational1.simplify()
print(simplified)  

rational2 = RationalNumber(5, 6)
rational2.mathFormat
rational3 = RationalNumber(7, 8)
rational3.mathFormat

# Suma
RationalNumber.sum(rational1, rational2)
# Resta
RationalNumber.substract(rational1, rational2)
# Producto
RationalNumber.product(rational1, rational2)
# División
RationalNumber.division(rational1, rational2)

# Generando una fracción aleatoria
random_rational = RationalNumber.random()
random_rational.mathFormat

# Creando ceros y unos 
zero_rational = RationalNumber.zero()
one_rational = RationalNumber.one()
zero_rational.mathFormat  
one_rational.mathFormat

# Convertir un número real a una fracción
fraction_from_real = RationalNumber.fromRealNumber(0.12) 
fraction_from_real.mathFormat

16 / 4
False
Fraccion resultante simplificada: 
4.0 / 1.0


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

116 / 24 = 4.833333333333333
76 / 24 = 3.1666666666666665
80 / 24 = 3.3333333333333335
96 / 20 = 4.8


<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

### Ejercicio 7:
Crea una clase llamada `Rectangle` que tenga como atributos `height`, `base` y `color`. Implemente metodos para el `area` y el `perimeter`. Ademas, implemente un:
* Metodo estatico llamado `are_equal` que verifique si dos rectangulos son iguales
* Metodo de clase llamado `random_rectangle` que genere un los valores aleatorios (1-10) de un objeto rectangulo 

![](IMG/rectangulo.png)

In [131]:
class Rectangle(object):
    '''
    Clase para trabajar con rectangulos
    '''
    def __init__(self,base = 1,height = 1,color = "blue"):
        self.height = height
        self.base = base
        self.color = color
    
    @property
    def area(self):
        return self.height * self.base
    
    @property
    def perimeter(self):
        return 2 * self.height + 2 * self.base
    
    def is_base_big(self, min = 5):
        if self.base > min:
            return True
        return False
    def __str__(self):
        return ("Base: {}\nAltura: {}".format(self.base,self.height))
    
    @staticmethod
    def are_equal(rect1, rect2):
        return True if rect1.base() == rect2.base() and rect1.perimeter() == rect2.perimeter() else False
    
    @classmethod
    def random_rectangle(cls):
        from numpy import random
        base = random.randint(1,10)
        height = random.randint(1,10)
        return cls(base,height)
            
        

### Ejercicio 8:

Dada la clase `Point2D`, crea la clase `Point3D` que hereda de `Point2D`. 

Modifica todos los métodos y usa el método `.super()` donde sea necesario para poder usarlos con puntos de 3 dimensiones.

![](IMG/3d.jpeg)


In [132]:
class Point2D():
  
  def __init__(self, x, y):
    self.x = x
    self.y = y

  def __str__(self):
    return "({}, {})".format(self.x, self.y)

  @classmethod
  def zero(cls):
    return cls(0, 0)
  
#Respuesta
class Point3D(Point2D):

    def __init__(self, x, y, z):
        super().__init__(x, y)
        self.z = z

    def __str__(self):
        return super().__str__()[:-1] + ", {})".format(self.z)
    
    @classmethod
    def zero(cls):
        return cls(0,0,0)

q = Point3D(1,2,3)
print(q)

cero3D = Point3D.zero()
print(cero3D)

(1, 2, 3)
(0, 0, 0)


### Ejercicio 9:

Dadas las clases `Triangle` y `Square`, crea la clase `Pyramid` que herede de las dos anteriores.

Implementa el constructor, el método `.area()` y el método `.volume()` usando el método `.super()` donde sea necesario para poder construir una pirámide regular con base cuadrada y calcular correctamente el área y el volumen.

![](IMG/piramide.png)

In [175]:
class Square():
  def __init__(self, base):
    self.base = base

  @property
  def perimeter(self):
    return 4 * self.base

  @property
  def area(self):
    return self.base * self.base

class Triangle():
  def __init__(self, base, height):
    self.base = base
    self.height = height
  
  @property
  def area(self):
    return 0.5 * self.base * self.height
  

class Pyramid(Square, Triangle):
  def __init__(self, base, height):
    super().__init__(base)
    self.height = height

  @property
  def alt_triang(self):
    from math import sqrt
    return sqrt((self.base/2)**2 + self.height ** 2)#Pitagoras
    
  @property
  def area(self):
    base_area = super().area
    base_permieter = super().perimeter
    area_lateral = 0.5 * base_permieter * self.alt_triang
    return area_lateral + base_area
    
  @property
  def volume(self):
    base_area = super().area
    return base_area * self.height / 3
    
#Prueba:
p = Pyramid(2, 2)
print("Area =",p.area)
print("Volumen =",p.volume)

Area = 12.94427190999916
Volumen = 2.6666666666666665


### Ejercicio 10:
* Crea una clase llamada `Punto` con sus dos coordenadas `X` e `Y`.
* Añade un método constructor para crear puntos fácilmente. Si no se reciben una coordenada, su valor será cero.
* Sobreescribe el método string, para que al imprimir por pantalla un punto aparezca en formato (X,Y)
* Añade un método llamado cuadrante que indique a qué cuadrante pertenece el punto, teniendo en cuenta que si X == 0 e Y != 0 se sitúa sobre el eje Y, si X != 0 e Y == 0 se sitúa sobre el eje X y si X == 0 e Y == 0 está sobre el origen.
* Añade un método llamado vector, que tome otro punto y calcule el vector resultante entre los dos puntos.
(Optativo) Añade un método llamado distancia, que tome otro punto y calcule la distancia entre los dos puntos y la muestre por pantalla. La fórmula es la siguiente:
$$d = \sqrt{(x_{2}-x_{1})^{2}-(y_{2}-y_{1})^{2}}$$

* Crea una clase llamada Rectangulo con dos puntos (inicial y final) que formarán la diagonal del rectángulo.
* Añade un método constructor para crear ambos puntos fácilmente, si no se envían se crearán dos puntos en el origen por defecto.
* Añade al rectángulo un método llamado base que muestre la base.
* Añade al rectángulo un método llamado altura que muestre la altura.
* Añade al rectángulo un método llamado area que muestre el area.

In [ ]:
#Pendiente